### ISSUE TITLE
[Feature Request] Add pie chart

### ISSUE THREAD

**Issue by pachi** [plotters-rs/plotters#207]
### What is the feature ?
Add pie charts.

### (Optional) Why this feature is useful and how people would use the feature ?

This is usefult to represent the parts in a whole.

### (Optional) Additional Information

Matplotlib has pie chart that could be used as a reference

https://matplotlib.org/3.1.1/gallery/pie_and_polar_charts/pie_features.html

**Comment by hhamana** [comment]
I'm interested in picking this one up. but I'm not sure what  approach can even be possible.
I was originally thinking of making up a triangle for each of those slices, rotate accordingly, and use a circle as mask to round off the edges, but 
- I can't find how to rotate a shape
- looks like using a shape as a mask isn't possible
Another approach would be defining a circular drawing area, and putting the triangles in there to be cropped accordingly, but that's not going to happen either.
Yet again another idea, giving up on circles and triangles, and just looking at building those with polygons, with ideally a curved line for the arc part (Polygon doesn't support curved lines, so that may be at best defined as 1px lines going along the radius?).

I'm just coming up with worse and worse ideas, and even those don't seem to be easily feasible. 
Nevermind allowing something such as exploding a slice, or nested pies.

Can anyone more experienced give some sort of guidance on how that could be implemented?
