### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by kaimast** [plotters-rs/plotters#333]
Hi,

I am considering using this to plot some graphs, but I noticed that none of the pull requests of the last four-ish months have been merged. 
Is this project still actively being maintained?

**Comment by AaronErhardt** [comment]
@38 what's your plan with this project?
I can totally understand that you don't have time to maintain plotters or want to work on something else, but letting the code rot here while there are people still sending PRs is not a good solution.
You could at least ask the community if somebody want's to step up as a new maintainer.

**Comment by lquenti** [comment]
Jup, otherwise the biggest plotting library will end up in fork hell.

I guess I'm going to plotlib

**Comment by lquenti** [comment]
Any other recommendations for stable plotting libraries?

**Comment by Bromeon** [comment]
> Any other recommendations for stable plotting libraries?

Not strictly plotting, but I've migrated away to [**egui**](https://github.com/emilk/egui), which is an immediate GUI library with some plotting capabilities.

There are still quite a few missing plot features though, and since it's immediate-mode, you have to pass in the data again every frame, so the approach is a bit different. But at least the library is actively being developed, with many contributors.

**Comment by lquenti** [comment]
Great to see that we can compare to the legendary imgui! But sadly too many non-rust dependencies which makes deployment impossible in some cases :(

**Comment by AaronErhardt** [comment]
I've contacted @38 via email two weeks ago and didn't get a response. I think it's save to say that this repository won't receive any updates anytime soon and @38 won't take care of finding a maintainer.

It looks like a fork is unavoidable if we don't want to let this code rot here forever. 

So the big questions are: 

+ Is anyone willing to step up as a maintainer?
+ Are there already active forks?
+ How do we communicate the changes and what name do we want to choose (the "plotters" name is already taken of course)?

**Comment by AaronErhardt** [comment]
FYI https://aaronerhardt.github.io/blog/posts/plotters_future/

**Comment by Be-ing** [comment]
Does anyone have a suggestion for a new crate name for a fork?

**Comment by Be-ing** [comment]
@38 has recently committed to [this repository](https://github.com/38/d4-format). Maybe try opening an issue there to get in contact?

**Comment by aliadnani** [comment]
> Does anyone have a suggestions for a new crate name for a fork?

plott-rs? 😁

**Comment by LeCyberDucky** [comment]
Hi, I just want to chime in to suggest taking it easy with the contact attempts. As is evident from their profile, @38 appears to be active on GitHub. Therefore, I think it's unlikely that they aren't aware of the e-mails being sent and issues being opened in this repository. I guess they may simply not be interested in responding at the moment, for one reason or another. I think we should respect that, instead of starting new creative contact attempts, like opening issues in unrelated repositories. 

Of course, it's far from ideal that a project like this, with a lot of public interest, is left unmaintained at the moment. But ultimately, it's okay for @38 to not interact here at the moment, if they don't feel like doing so. This is free, open source work after all. 

In case @38 is following this discussion, I would also like to mention the Rust Bus project as another option: 

https://github.com/rust-bus
https://users.rust-lang.org/t/bus-factor-1-for-crates/17046

By running `cargo owner --add rust-bus-owner`, a set of volunteers will be added to the project, in order to ensure that it doesn't go unmaintained. To me, that looks like the best option at the moment.

**Comment by AaronErhardt** [comment]
A fork is open now #341 :rocket:

**Comment by 38** [comment]
I opened a call for participation issue and closes this one.
