### ISSUE TITLE
A FORK TO CONTINUE THE DEVELOPMENT IS OPEN NOW

### ISSUE THREAD

**Issue by AaronErhardt** [plotters-rs/plotters#341]
Since the future of this repository is unclear I created a fork to continue the development as an interim solution. For now, the plan is to merge any changes into this repository eventually. If that doesn't work a permanent solution must be found.

**Pull requests are welcome!**

[**plot-rs/plotters**](https://github.com/plot-rs/plotters)

You can also join the new [plot-rs](https://github.com/plot-rs) organization. Just send me a short message if you want to join.

**Comment by tronical** [comment]
Thanks for the initiative @AaronErhardt . Since there are multiple crates involved, perhaps it would make sense to maintain the fork under an organisation? 

That way there'd also be a unification, as right now plotters is here and the other crates are under https://github.com/plotters-rs .

I think ideally all related/dependent crates would be under one organization on GitHub.

**Comment by ogoffart** [comment]
(I wonder if it is so wise to split all the crates in many repository. Perhaps it would be easier to merge them all in one workspace repository. But maybe that's just because i'm a fan of mono-repos)

**Comment by AaronErhardt** [comment]
I've created a new organization now and updated the link. A monorepo could have some advantages but if we want to reunite the repositories eventually, this might make things complicated. If that becomes the permanent solution we can think about this again.

**Comment by Be-ing** [comment]
I noticed you haven't changed the crate name. Do you not plan to publish the fork to crates.io?

**Comment by AaronErhardt** [comment]
plot-rs is already reserved as a name, but I want to wait a little bit for things to settle. I still hope we can continue under the name plotters. Also, we first need a reasonable amount of improvements before a new release makes sense.

**Comment by LeCyberDucky** [comment]
It's great to see some progress here. Thanks for setting things in motion! 

I'm aware that this is supposed to be an interim solution, but, in many cases, there's "nothing more permanent than a temporary solution". Just in case no neat resolution is found (i.e. the original repo remains inactive), I would like to suggest to consider adding the fork to the [Rust Bus project](https://github.com/rust-bus), as I mentioned in https://github.com/38/plotters/issues/333#issuecomment-1097921841. It would be a shame to eventually end up in a situation where another fork of this new fork is needed.

**Comment by hhamana** [comment]
Thank you so much fro stepping in, after close to one year since the last sign of life (on this repo) from the maintainer.
It's unfortunate that the community is left to deal with it, with no real guidance from someone who would know the ins and out of the codebase.
But again, thank god for FOSS that we can have a shot at keeping it rolling.

**Comment by 38** [comment]
Hi Thanks everyone, I don't have bandwidth to maintain the package currently due to some personal issues. 
I am very sorry for the inconvenience of you guys during my absence.  

I think it's better for the package to have a development team, not only me. Actually I have an organization for https://github.com/orgs/plotters-rs. And I think I am going to transfer the ownership of the package to that organization. And I am calling for participation: I am looking for who want to help me to provide better support for this crate.

Please let me know if you are interested in such a role. Thanks in advance.

Hao

**Comment by AaronErhardt** [comment]
@38 thanks for your response! You've really done an awesome job with this crate and it would have been a shame if we had use a fork permanently.

I hope it wasn't a bit too eager trying to get your attention and I wish you best of luck regarding your personal situation.

Btw. I could write a small blog post we can post on Reddit and TWIR for example to get more people on board.

**Comment by 38** [comment]
> Btw. I could write a small blog post we can post on Reddit and TWIR for example to get more people on board.

That's awesome, also once this project is under community maintenance, I think we need to at least setup a place for discussion, like gitter or slack. 

After that I will keep on an eye on how the community maintenance approach goes. Then I think I would like to focus on less development and maintenance but more testing, publishing and versioning, as I don't think I will be as active as past. 

Hope this would work for everyone. And I am glad there are people want to help.

Cheers!

**Comment by 38** [comment]
I opened a call for participation issue and closes this one.

**Comment by pricesmith** [comment]
> I opened a call for participation issue and closes this one.

Pretty late here-- where is this call for participation?
