### ISSUE TITLE
[BUG] Latest version `v0.3.5` is not published on Crates.io

### ISSUE THREAD

**Issue by seongs1024** [plotters-rs/plotters#453]
**Describe the bug**

The version of `plotters` on crates.io is `v0.3.4`.

**Comment by StormBytePP** [comment]
+1 as this is a dep on another stuff which currently build up against git version

**Comment by jayvdb** [comment]
This is now critical because of https://github.com/plotters-rs/plotters/issues/461 , as it now occurs on stable 1.70 just released.

**Comment by AaronErhardt** [comment]
FYI there's nothing anyone can do except @38 which is the only person who can publish on crates.io. @38 has been inactive for several months again so probably this won't be addressed very soon...

**Comment by jayvdb** [comment]
I have emailed @38 two days ago.  If this project remains without an active maintainer, we need to list it as unmaintained ; c.f. https://github.com/rustsec/advisory-db/blob/main/HOWTO_UNMAINTAINED.md

**Comment by madchicken** [comment]
Sorry for the dumb question: if this crate goes "unmaintained" what is our best option? A fork?
Also, how much should we wait before declaring this repo stale?

**Comment by jayvdb** [comment]
ya, given the last activity for @38 was in [Sept 2022](https://github.com/plotters-rs/plotters/commits?author=38), ~nine months ago, a fork is probably required.

@AaronErhardt @facorread , you are both listed as "People" on https://github.com/plotters-rs , do either of you have git commit or crate publish rights?

**Comment by AaronErhardt** [comment]
This is a quick breakdown of what happened a couple of months ago:

+ plotters was inactive for over a year, not a single commit merged
+ Me and a couple of others tried to reach out to @38
+ A fork was created to merge the most important fixes
+ After some time, @38 responded and added a couple of people to the plotters organization so they could manage this repo
+ The fork was merged into the main repo and then deleted
+ Then, @38 became inactive again, which means that releases on crates.io are not possible

This repo is not stale, however, the problem is just the crate ownership on crates.io. I've reserved the name ["plot-rs"](https://crates.io/crates/plot-rs) back then in case we need another crate name to publish new releases of crates.io. I'm not sure how long we should wait though, since there are a lot of problems with the latest stable Rust releases. In any case, I would really appreciate some support (for doing the releases and announcing it etc.) because I don't have a lot of time currently.

**Comment by 38** [comment]
Hi all, 

Sorry for the delay, I would like to add @AaronErhardt to owner on crates.io as I really don't have the bandwidth for the maintenance. 

@AaronErhardt, please let me know your user name on crates.io so that I can move forward.

Thanks!

**Comment by AaronErhardt** [comment]
Hi @38,

don't worry about the delay. We truly appreciate your work on this outstanding crate. It would just be a shame if we would let all this code become stale and couldn't address newly discovered problems.

My name on crates.io is also [AaronErhardt](https://crates.io/users/AaronErhardt). Also note, that I can't maintain all plotters repositories yet, which prevented me from merging PRs like [this](https://github.com/plotters-rs/plotters-gtk-demo/pull/2).

In the name of the community, I want to say thanks for all your efforts and for allowing us to move forward with plotters!

**Comment by 38** [comment]
@AaronErhardt, thanks for all the works! I've add you as the owner on crates.io. Also I changed your role in this organization to owner as well, so this should allow you do all the PRs. 

Please let me know if you need anything else.

**Comment by AaronErhardt** [comment]
Thanks @38, that will already help a lot. However, there is not just the plotters crate, but the various backends so being able to manage those on crates.io would be helpful, too.

**Comment by 38** [comment]
Sure, I just invited you as owner for those crates too. Please let me know if anything is missing. Thanks!

**Comment by AaronErhardt** [comment]
Thanks! That should be all. I'll do a release later this wekk.

**Comment by AaronErhardt** [comment]
Version 0.3.5 is live on crates.io :tada::tada::tada:

Of course, let me know if there have been any regressions with the new version.
