### ISSUE TITLE
Rapid development of plotters

### ISSUE THREAD

**Issue by wangjiawen2013** [plotters-rs/plotters#546]
Hi guys,

As the development of plotters is stagnating, there are two newly emerging rust visualization library based on Echarts, hope peopel who are eagering to plot can use these three tools as needed.

https://github.com/vicanso/charts-rs
https://github.com/yuankunzhang/charming

It should be pointed out that charts-rs is under active maintenance now. hope plotters and charming develop rapidly like charts-rs.

**Comment by AaronErhardt** [comment]
I don't think it makes sense to open an issue for this because comparing different crates simply isn't something that can be fixed.

It's correct that the development of plotters has slowed down significantly, but if you want to help people to find alternatives, please provide a PR that lists those in the README.

**Comment by wangjiawen2013** [comment]
@AaronErhardt 
Thanks for you maintenance  !
Now I am testing some more advanced examples by combining polars and plotters and have made great progress. I'll pull a request when I finish it.
